graphicalMode: false
incubationRate: 0.3
infectionRate: 0.2
looseImmunityRate: 0.09
recoveryRate: 0.6
nbOfCycles: 300
nbOfPatientZero: 10
population: 5000
seed: 120
size: 500
synchronousMode: true
timeBetweenCycles: 0
infectionStacks : false