seed : 120
population : 10000 #number of agents
size : 500 #size of the world in pixels
nbOfPatientZero : 1
infectionChance : 0.1 #percentage of chance that an infected agent will spread to a susceptible agent
incubationRate : 0.5 #chance that an exposed agent become infected each cycle
recoveryRate : 0.05 #chance that an infected agent become recovered each cycle
nbOfCycles : -1 #if the number is negative, will run endlessly
synchronousMode : false #if true, will wake synchronously the agents in a pseudo-random order based on the given seed otherwise will wake up the agents asynchronously