graphicalMode: true
incubationRate: 0.33
infectionRate: 0.5
looseImmunityRate: 0.0027
recoveryRate: 0.10
nbOfCycles: 720
nbOfPatientZero: 1
population: 1000
recordExperiment: false
playRecord: false
seed: 120
size: 400
wrappingWorld : true
synchronousMode: false
timeBetweenCycles: 0
infectionStacks : true
threePhased : false