graphicalMode: true
incubationRate: 0.3
infectionRate: 0.8
looseImmunityRate: 0.008
recoveryRate: 0.14
nbOfCycles: 2000
nbOfPatientZero: 1
population: 3000
recordExperiment: false
playRecord: false
seed: 120
size: 1000
wrappingWorld : true
synchronousMode: false
timeBetweenCycles: 0
infectionStacks : false
threePhased : false