graphicalMode: true
incubationRate: 0.3
infectionRate: 0.035
looseImmunityRate: 0.09
recoveryRate: 0.6
nbOfCycles: 2000
nbOfPatientZero: 10
population: 5000
seed: 120
size: 500
synchronousMode: false
timeBetweenCycles: 0
