graphicalMode: true
incubationRate: 0.3
infectionRate: 0.75
looseImmunityRate: 0.008
recoveryRate: 0.1429
nbOfCycles: 2000
nbOfPatientZero: 1
population: 3000
seed: 120
size: 1000
synchronousMode: false
timeBetweenCycles: 0
infectionStacks : true