seed : 120
population : 3000 #number of agents
size : 500 #size of the world in pixels
nbOfPatientZero : 1
infectionRate : 0.05 #chance that an infected agent will spread to a susceptible agent
incubationRate : 0.5 #chance that an exposed agent become infected each cycle
recoveryRate : 0.05 #chance that an infected agent become recovered each cycle
looseImmunityRate : 0.01 #chance that a recovered agent become suceptible again
nbOfCycles : -1 #if the number is negative, will run endlessly
synchronousMode : true #if true, will wake synchronously the agents in a pseudo-random order based on the given seed otherwise will wake up the agents asynchronously